### ISSUE TITLE
Wrong Address

### ISSUE THREAD

**Issue by silsha** [eskerda/cmdbikes#2]
The address of VRNnextbike (Mannheim, Germany) is always shown as „Florida, USA“.
![image](https://cloud.githubusercontent.com/assets/31850/24850774/9a9cde80-1dd1-11e7-9fb3-1300050babb6.png)

**Comment by PabloCastellano** [comment]
I have a similar situation. How does it really work?
I'm looking for bikes in a street in Barcelona but the first result I get is a different street (in Barcelona too)

```
$ cmdbikes show "Avinguda Diagonal"
Found network: Bicing, Barcelona (ES)
 374 - Pg. De Gràcia, 89
 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
 0 bikes               32 slots
```

**Comment by eskerda** [comment]
Since address lookup uses a geocoder, it's better to give the program some context, for example your city and country: "Avinguda Diagonal, Barcelona"
